



POST http://127.0.0.1:5000/get_dataCenterId
Content-Type: application/json

{
  "client_name": "thanoon",
  "data": {
    "TaskFileSize": 152,
    "TaskOutputFileSize": 11,
    "TaskFileLength": 424,
    "UserLatitude": 11,
    "UserLongitude": 11
  }
}
